name: Upload all src-html to Bunny.net Storage

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src-html/*'

permissions:
  id-token: write
  contents: read

jobs:
  upload-all-to-bunny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Bunny.net storage zone
        env:
          BUNNY_STORAGE_ZONE: ${{ secrets.BUNNY_STORAGE_ZONE }}
          BUNNY_STORAGE_HOST: ${{ secrets.BUNNY_STORAGE_HOST }}
          BUNNY_STORAGE_API_KEY: ${{ secrets.BUNNY_STORAGE_API_KEY }}
        run: |
          # List all files in the storage zone
          FILES=$(curl -s -H "AccessKey: $BUNNY_STORAGE_API_KEY" "https://$BUNNY_STORAGE_HOST/$BUNNY_STORAGE_ZONE/?list" | jq -r '.[].ObjectName')
          for file in $FILES; do
            curl -X DELETE \
              -H "AccessKey: $BUNNY_STORAGE_API_KEY" \
              "https://$BUNNY_STORAGE_HOST/$BUNNY_STORAGE_ZONE/$file"
          done
        shell: bash

      - name: Upload all files from src-html to Bunny.net
        env:
          BUNNY_STORAGE_ZONE: ${{ secrets.BUNNY_STORAGE_ZONE }}
          BUNNY_STORAGE_HOST: ${{ secrets.BUNNY_STORAGE_HOST }}
          BUNNY_STORAGE_API_KEY: ${{ secrets.BUNNY_STORAGE_API_KEY }}
        run: |
          find src-html -type f | while read file; do
            REL_PATH="${file#src-html/}"
            curl --request PUT \
              --url "https://$BUNNY_STORAGE_HOST/$BUNNY_STORAGE_ZONE/$REL_PATH" \
              --header "AccessKey: $BUNNY_STORAGE_API_KEY" \
              --header "Content-Type: application/octet-stream" \
              --header "accept: application/json" \
              --data-binary @"$file"
          done
        shell: bash